//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Input_ActionSet_Generic p_Generic;
        
        private static SteamVR_Input_ActionSet_Vive p_Vive;
        
        private static SteamVR_Input_ActionSet_OculusTouch p_OculusTouch;
        
        private static SteamVR_Input_ActionSet_WindowsMR p_WindowsMR;
        
        private static SteamVR_Input_ActionSet_Knuckles p_Knuckles;
        
        private static SteamVR_Input_ActionSet_Cosmos p_Cosmos;
        
        private static SteamVR_Input_ActionSet_PicoNeo p_PicoNeo;
        
        private static SteamVR_Input_ActionSet_HPReverb p_HPReverb;
        
        private static SteamVR_Input_ActionSet_Focus3 p_Focus3;
        
        public static SteamVR_Input_ActionSet_Generic Generic
        {
            get
            {
                return SteamVR_Actions.p_Generic.GetCopy<SteamVR_Input_ActionSet_Generic>();
            }
        }
        
        public static SteamVR_Input_ActionSet_Vive Vive
        {
            get
            {
                return SteamVR_Actions.p_Vive.GetCopy<SteamVR_Input_ActionSet_Vive>();
            }
        }
        
        public static SteamVR_Input_ActionSet_OculusTouch OculusTouch
        {
            get
            {
                return SteamVR_Actions.p_OculusTouch.GetCopy<SteamVR_Input_ActionSet_OculusTouch>();
            }
        }
        
        public static SteamVR_Input_ActionSet_WindowsMR WindowsMR
        {
            get
            {
                return SteamVR_Actions.p_WindowsMR.GetCopy<SteamVR_Input_ActionSet_WindowsMR>();
            }
        }
        
        public static SteamVR_Input_ActionSet_Knuckles Knuckles
        {
            get
            {
                return SteamVR_Actions.p_Knuckles.GetCopy<SteamVR_Input_ActionSet_Knuckles>();
            }
        }
        
        public static SteamVR_Input_ActionSet_Cosmos Cosmos
        {
            get
            {
                return SteamVR_Actions.p_Cosmos.GetCopy<SteamVR_Input_ActionSet_Cosmos>();
            }
        }
        
        public static SteamVR_Input_ActionSet_PicoNeo PicoNeo
        {
            get
            {
                return SteamVR_Actions.p_PicoNeo.GetCopy<SteamVR_Input_ActionSet_PicoNeo>();
            }
        }
        
        public static SteamVR_Input_ActionSet_HPReverb HPReverb
        {
            get
            {
                return SteamVR_Actions.p_HPReverb.GetCopy<SteamVR_Input_ActionSet_HPReverb>();
            }
        }
        
        public static SteamVR_Input_ActionSet_Focus3 Focus3
        {
            get
            {
                return SteamVR_Actions.p_Focus3.GetCopy<SteamVR_Input_ActionSet_Focus3>();
            }
        }
        
        private static void StartPreInitActionSets()
        {
            SteamVR_Actions.p_Generic = ((SteamVR_Input_ActionSet_Generic)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_Generic>("/actions/Generic")));
            SteamVR_Actions.p_Vive = ((SteamVR_Input_ActionSet_Vive)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_Vive>("/actions/Vive")));
            SteamVR_Actions.p_OculusTouch = ((SteamVR_Input_ActionSet_OculusTouch)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_OculusTouch>("/actions/OculusTouch")));
            SteamVR_Actions.p_WindowsMR = ((SteamVR_Input_ActionSet_WindowsMR)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_WindowsMR>("/actions/WindowsMR")));
            SteamVR_Actions.p_Knuckles = ((SteamVR_Input_ActionSet_Knuckles)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_Knuckles>("/actions/Knuckles")));
            SteamVR_Actions.p_Cosmos = ((SteamVR_Input_ActionSet_Cosmos)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_Cosmos>("/actions/Cosmos")));
            SteamVR_Actions.p_PicoNeo = ((SteamVR_Input_ActionSet_PicoNeo)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_PicoNeo>("/actions/PicoNeo")));
            SteamVR_Actions.p_HPReverb = ((SteamVR_Input_ActionSet_HPReverb)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_HPReverb>("/actions/HPReverb")));
            SteamVR_Actions.p_Focus3 = ((SteamVR_Input_ActionSet_Focus3)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_Focus3>("/actions/Focus3")));
            Valve.VR.SteamVR_Input.actionSets = new Valve.VR.SteamVR_ActionSet[] {
                    SteamVR_Actions.Generic,
                    SteamVR_Actions.Vive,
                    SteamVR_Actions.OculusTouch,
                    SteamVR_Actions.WindowsMR,
                    SteamVR_Actions.Knuckles,
                    SteamVR_Actions.Cosmos,
                    SteamVR_Actions.PicoNeo,
                    SteamVR_Actions.HPReverb,
                    SteamVR_Actions.Focus3};
        }
    }
}
