//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Action_Pose p_generic_Pose;
        
        private static SteamVR_Action_Single p_generic_Strength;
        
        private static SteamVR_Action_Vector2 p_generic_Axis;
        
        private static SteamVR_Action_Boolean p_generic_TouchingStrength;
        
        private static SteamVR_Action_Boolean p_generic_TouchingAxis;
        
        private static SteamVR_Action_Boolean p_generic_ActionPrimary;
        
        private static SteamVR_Action_Boolean p_generic_ActionSecondary;
        
        private static SteamVR_Action_Boolean p_generic_ActionGrab;
        
        private static SteamVR_Action_Boolean p_generic_ActionMenu;
        
        private static SteamVR_Action_Skeleton p_generic_LeftHand;
        
        private static SteamVR_Action_Skeleton p_generic_RightHand;
        
        private static SteamVR_Action_Boolean p_generic_UserPresent;
        
        private static SteamVR_Action_Vibration p_generic_Haptic;
        
        private static SteamVR_Action_Boolean p_vive_trigger_hair;
        
        private static SteamVR_Action_Boolean p_vive_trigger_click;
        
        private static SteamVR_Action_Single p_vive_trigger;
        
        private static SteamVR_Action_Boolean p_vive_touchpad_touch;
        
        private static SteamVR_Action_Boolean p_vive_touchpad_click;
        
        private static SteamVR_Action_Vector2 p_vive_touchpad;
        
        private static SteamVR_Action_Boolean p_vive_grip;
        
        private static SteamVR_Action_Boolean p_vive_app;
        
        private static SteamVR_Action_Pose p_vive_pose;
        
        private static SteamVR_Action_Skeleton p_vive_left_hand;
        
        private static SteamVR_Action_Skeleton p_vive_right_hand;
        
        private static SteamVR_Action_Vibration p_vive_haptic;
        
        private static SteamVR_Action_Boolean p_oculusTouch_start;
        
        private static SteamVR_Action_Boolean p_oculusTouch_button_YB;
        
        private static SteamVR_Action_Boolean p_oculusTouch_button_XA;
        
        private static SteamVR_Action_Boolean p_oculusTouch_button_YB_touch;
        
        private static SteamVR_Action_Boolean p_oculusTouch_button_XA_touch;
        
        private static SteamVR_Action_Boolean p_oculusTouch_thumbrest_touch;
        
        private static SteamVR_Action_Single p_oculusTouch_grip;
        
        private static SteamVR_Action_Boolean p_oculusTouch_grip_click;
        
        private static SteamVR_Action_Vector2 p_oculusTouch_joystick;
        
        private static SteamVR_Action_Boolean p_oculusTouch_joystick_touch;
        
        private static SteamVR_Action_Boolean p_oculusTouch_joystick_click;
        
        private static SteamVR_Action_Single p_oculusTouch_trigger;
        
        private static SteamVR_Action_Boolean p_oculusTouch_trigger_touch;
        
        private static SteamVR_Action_Boolean p_oculusTouch_trigger_click;
        
        private static SteamVR_Action_Pose p_oculusTouch_pose;
        
        private static SteamVR_Action_Skeleton p_oculusTouch_left_hand;
        
        private static SteamVR_Action_Skeleton p_oculusTouch_right_hand;
        
        private static SteamVR_Action_Vibration p_oculusTouch_haptic;
        
        private static SteamVR_Action_Boolean p_windowsMR_grip;
        
        private static SteamVR_Action_Boolean p_windowsMR_app;
        
        private static SteamVR_Action_Boolean p_windowsMR_trigger_hair;
        
        private static SteamVR_Action_Boolean p_windowsMR_trigger_click;
        
        private static SteamVR_Action_Single p_windowsMR_trigger;
        
        private static SteamVR_Action_Vector2 p_windowsMR_touchpad;
        
        private static SteamVR_Action_Boolean p_windowsMR_touchpad_touch;
        
        private static SteamVR_Action_Boolean p_windowsMR_touchpad_click;
        
        private static SteamVR_Action_Vector2 p_windowsMR_joystick;
        
        private static SteamVR_Action_Pose p_windowsMR_pose;
        
        private static SteamVR_Action_Skeleton p_windowsMR_left_hand;
        
        private static SteamVR_Action_Skeleton p_windowsMR_right_hand;
        
        private static SteamVR_Action_Vibration p_windowsMR_haptic;
        
        private static SteamVR_Action_Single p_knuckles_grip;
        
        private static SteamVR_Action_Boolean p_knuckles_grip_touch;
        
        private static SteamVR_Action_Boolean p_knuckles_button_A;
        
        private static SteamVR_Action_Boolean p_knuckles_button_B;
        
        private static SteamVR_Action_Boolean p_knuckles_button_A_touch;
        
        private static SteamVR_Action_Boolean p_knuckles_button_B_touch;
        
        private static SteamVR_Action_Single p_knuckles_trigger;
        
        private static SteamVR_Action_Boolean p_knuckles_trigger_touch;
        
        private static SteamVR_Action_Boolean p_knuckles_trigger_click;
        
        private static SteamVR_Action_Vector2 p_knuckles_joystick;
        
        private static SteamVR_Action_Boolean p_knuckles_joystick_touch;
        
        private static SteamVR_Action_Boolean p_knuckles_joystick_click;
        
        private static SteamVR_Action_Vector2 p_knuckles_touchpad;
        
        private static SteamVR_Action_Boolean p_knuckles_touchpad_touch;
        
        private static SteamVR_Action_Boolean p_knuckles_touchpad_press;
        
        private static SteamVR_Action_Pose p_knuckles_pose;
        
        private static SteamVR_Action_Boolean p_knuckles_grip_click;
        
        private static SteamVR_Action_Single p_knuckles_touchpad_force;
        
        private static SteamVR_Action_Skeleton p_knuckles_left_hand;
        
        private static SteamVR_Action_Skeleton p_knuckles_right_hand;
        
        private static SteamVR_Action_Vibration p_knuckles_haptic;
        
        private static SteamVR_Action_Vector2 p_cosmos_joystick;
        
        private static SteamVR_Action_Boolean p_cosmos_joystick_touch;
        
        private static SteamVR_Action_Boolean p_cosmos_joystick_click;
        
        private static SteamVR_Action_Single p_cosmos_trigger;
        
        private static SteamVR_Action_Boolean p_cosmos_trigger_touch;
        
        private static SteamVR_Action_Boolean p_cosmos_trigger_click;
        
        private static SteamVR_Action_Boolean p_cosmos_grip_click;
        
        private static SteamVR_Action_Boolean p_cosmos_menu;
        
        private static SteamVR_Action_Boolean p_cosmos_buttonAX;
        
        private static SteamVR_Action_Boolean p_cosmos_buttonBY;
        
        private static SteamVR_Action_Boolean p_cosmos_bumper;
        
        private static SteamVR_Action_Skeleton p_cosmos_left_hand;
        
        private static SteamVR_Action_Skeleton p_cosmos_right_hand;
        
        private static SteamVR_Action_Pose p_cosmos_pose;
        
        private static SteamVR_Action_Vibration p_cosmos_haptic;
        
        private static SteamVR_Action_Vector2 p_picoNeo_thumbstick;
        
        private static SteamVR_Action_Boolean p_picoNeo_thumbstick_touch;
        
        private static SteamVR_Action_Boolean p_picoNeo_thumbstick_click;
        
        private static SteamVR_Action_Single p_picoNeo_trigger;
        
        private static SteamVR_Action_Boolean p_picoNeo_trigger_click;
        
        private static SteamVR_Action_Boolean p_picoNeo_grip_click;
        
        private static SteamVR_Action_Boolean p_picoNeo_app;
        
        private static SteamVR_Action_Boolean p_picoNeo_system;
        
        private static SteamVR_Action_Boolean p_picoNeo_buttonYB;
        
        private static SteamVR_Action_Boolean p_picoNeo_buttonXA;
        
        private static SteamVR_Action_Skeleton p_picoNeo_left_hand;
        
        private static SteamVR_Action_Skeleton p_picoNeo_right_hand;
        
        private static SteamVR_Action_Pose p_picoNeo_pose;
        
        private static SteamVR_Action_Vibration p_picoNeo_haptic;
        
        private static SteamVR_Action_Boolean p_hPReverb_appmenu;
        
        private static SteamVR_Action_Boolean p_hPReverb_button_YB;
        
        private static SteamVR_Action_Boolean p_hPReverb_button_XA;
        
        private static SteamVR_Action_Single p_hPReverb_grip;
        
        private static SteamVR_Action_Boolean p_hPReverb_grip_click;
        
        private static SteamVR_Action_Boolean p_hPReverb_grip_touch;
        
        private static SteamVR_Action_Vector2 p_hPReverb_joystick;
        
        private static SteamVR_Action_Boolean p_hPReverb_joystick_click;
        
        private static SteamVR_Action_Single p_hPReverb_trigger;
        
        private static SteamVR_Action_Boolean p_hPReverb_trigger_click;
        
        private static SteamVR_Action_Pose p_hPReverb_pose;
        
        private static SteamVR_Action_Skeleton p_hPReverb_left_hand;
        
        private static SteamVR_Action_Skeleton p_hPReverb_right_hand;
        
        private static SteamVR_Action_Vibration p_hPReverb_haptic;
        
        private static SteamVR_Action_Vector2 p_focus3_joystick;
        
        private static SteamVR_Action_Boolean p_focus3_joystick_touch;
        
        private static SteamVR_Action_Boolean p_focus3_joystick_click;
        
        private static SteamVR_Action_Single p_focus3_trigger;
        
        private static SteamVR_Action_Boolean p_focus3_trigger_touch;
        
        private static SteamVR_Action_Boolean p_focus3_trigger_click;
        
        private static SteamVR_Action_Single p_focus3_grip;
        
        private static SteamVR_Action_Boolean p_focus3_grip_touch;
        
        private static SteamVR_Action_Boolean p_focus3_grip_click;
        
        private static SteamVR_Action_Boolean p_focus3_button_a;
        
        private static SteamVR_Action_Boolean p_focus3_button_b;
        
        private static SteamVR_Action_Boolean p_focus3_button_x;
        
        private static SteamVR_Action_Boolean p_focus3_button_y;
        
        private static SteamVR_Action_Boolean p_focus3_menu;
        
        private static SteamVR_Action_Boolean p_focus3_parking_touch;
        
        private static SteamVR_Action_Skeleton p_focus3_left_hand;
        
        private static SteamVR_Action_Skeleton p_focus3_right_hand;
        
        private static SteamVR_Action_Pose p_focus3_pose;
        
        private static SteamVR_Action_Vibration p_focus3_haptic;
        
        public static SteamVR_Action_Pose generic_Pose
        {
            get
            {
                return SteamVR_Actions.p_generic_Pose.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Single generic_Strength
        {
            get
            {
                return SteamVR_Actions.p_generic_Strength.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Vector2 generic_Axis
        {
            get
            {
                return SteamVR_Actions.p_generic_Axis.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Boolean generic_TouchingStrength
        {
            get
            {
                return SteamVR_Actions.p_generic_TouchingStrength.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean generic_TouchingAxis
        {
            get
            {
                return SteamVR_Actions.p_generic_TouchingAxis.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean generic_ActionPrimary
        {
            get
            {
                return SteamVR_Actions.p_generic_ActionPrimary.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean generic_ActionSecondary
        {
            get
            {
                return SteamVR_Actions.p_generic_ActionSecondary.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean generic_ActionGrab
        {
            get
            {
                return SteamVR_Actions.p_generic_ActionGrab.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean generic_ActionMenu
        {
            get
            {
                return SteamVR_Actions.p_generic_ActionMenu.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Skeleton generic_LeftHand
        {
            get
            {
                return SteamVR_Actions.p_generic_LeftHand.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Skeleton generic_RightHand
        {
            get
            {
                return SteamVR_Actions.p_generic_RightHand.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Boolean generic_UserPresent
        {
            get
            {
                return SteamVR_Actions.p_generic_UserPresent.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vibration generic_Haptic
        {
            get
            {
                return SteamVR_Actions.p_generic_Haptic.GetCopy<SteamVR_Action_Vibration>();
            }
        }
        
        public static SteamVR_Action_Boolean vive_trigger_hair
        {
            get
            {
                return SteamVR_Actions.p_vive_trigger_hair.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean vive_trigger_click
        {
            get
            {
                return SteamVR_Actions.p_vive_trigger_click.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Single vive_trigger
        {
            get
            {
                return SteamVR_Actions.p_vive_trigger.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Boolean vive_touchpad_touch
        {
            get
            {
                return SteamVR_Actions.p_vive_touchpad_touch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean vive_touchpad_click
        {
            get
            {
                return SteamVR_Actions.p_vive_touchpad_click.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vector2 vive_touchpad
        {
            get
            {
                return SteamVR_Actions.p_vive_touchpad.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Boolean vive_grip
        {
            get
            {
                return SteamVR_Actions.p_vive_grip.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean vive_app
        {
            get
            {
                return SteamVR_Actions.p_vive_app.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Pose vive_pose
        {
            get
            {
                return SteamVR_Actions.p_vive_pose.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Skeleton vive_left_hand
        {
            get
            {
                return SteamVR_Actions.p_vive_left_hand.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Skeleton vive_right_hand
        {
            get
            {
                return SteamVR_Actions.p_vive_right_hand.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Vibration vive_haptic
        {
            get
            {
                return SteamVR_Actions.p_vive_haptic.GetCopy<SteamVR_Action_Vibration>();
            }
        }
        
        public static SteamVR_Action_Boolean oculusTouch_start
        {
            get
            {
                return SteamVR_Actions.p_oculusTouch_start.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean oculusTouch_button_YB
        {
            get
            {
                return SteamVR_Actions.p_oculusTouch_button_YB.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean oculusTouch_button_XA
        {
            get
            {
                return SteamVR_Actions.p_oculusTouch_button_XA.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean oculusTouch_button_YB_touch
        {
            get
            {
                return SteamVR_Actions.p_oculusTouch_button_YB_touch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean oculusTouch_button_XA_touch
        {
            get
            {
                return SteamVR_Actions.p_oculusTouch_button_XA_touch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean oculusTouch_thumbrest_touch
        {
            get
            {
                return SteamVR_Actions.p_oculusTouch_thumbrest_touch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Single oculusTouch_grip
        {
            get
            {
                return SteamVR_Actions.p_oculusTouch_grip.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Boolean oculusTouch_grip_click
        {
            get
            {
                return SteamVR_Actions.p_oculusTouch_grip_click.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vector2 oculusTouch_joystick
        {
            get
            {
                return SteamVR_Actions.p_oculusTouch_joystick.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Boolean oculusTouch_joystick_touch
        {
            get
            {
                return SteamVR_Actions.p_oculusTouch_joystick_touch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean oculusTouch_joystick_click
        {
            get
            {
                return SteamVR_Actions.p_oculusTouch_joystick_click.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Single oculusTouch_trigger
        {
            get
            {
                return SteamVR_Actions.p_oculusTouch_trigger.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Boolean oculusTouch_trigger_touch
        {
            get
            {
                return SteamVR_Actions.p_oculusTouch_trigger_touch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean oculusTouch_trigger_click
        {
            get
            {
                return SteamVR_Actions.p_oculusTouch_trigger_click.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Pose oculusTouch_pose
        {
            get
            {
                return SteamVR_Actions.p_oculusTouch_pose.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Skeleton oculusTouch_left_hand
        {
            get
            {
                return SteamVR_Actions.p_oculusTouch_left_hand.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Skeleton oculusTouch_right_hand
        {
            get
            {
                return SteamVR_Actions.p_oculusTouch_right_hand.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Vibration oculusTouch_haptic
        {
            get
            {
                return SteamVR_Actions.p_oculusTouch_haptic.GetCopy<SteamVR_Action_Vibration>();
            }
        }
        
        public static SteamVR_Action_Boolean windowsMR_grip
        {
            get
            {
                return SteamVR_Actions.p_windowsMR_grip.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean windowsMR_app
        {
            get
            {
                return SteamVR_Actions.p_windowsMR_app.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean windowsMR_trigger_hair
        {
            get
            {
                return SteamVR_Actions.p_windowsMR_trigger_hair.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean windowsMR_trigger_click
        {
            get
            {
                return SteamVR_Actions.p_windowsMR_trigger_click.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Single windowsMR_trigger
        {
            get
            {
                return SteamVR_Actions.p_windowsMR_trigger.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Vector2 windowsMR_touchpad
        {
            get
            {
                return SteamVR_Actions.p_windowsMR_touchpad.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Boolean windowsMR_touchpad_touch
        {
            get
            {
                return SteamVR_Actions.p_windowsMR_touchpad_touch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean windowsMR_touchpad_click
        {
            get
            {
                return SteamVR_Actions.p_windowsMR_touchpad_click.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vector2 windowsMR_joystick
        {
            get
            {
                return SteamVR_Actions.p_windowsMR_joystick.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Pose windowsMR_pose
        {
            get
            {
                return SteamVR_Actions.p_windowsMR_pose.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Skeleton windowsMR_left_hand
        {
            get
            {
                return SteamVR_Actions.p_windowsMR_left_hand.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Skeleton windowsMR_right_hand
        {
            get
            {
                return SteamVR_Actions.p_windowsMR_right_hand.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Vibration windowsMR_haptic
        {
            get
            {
                return SteamVR_Actions.p_windowsMR_haptic.GetCopy<SteamVR_Action_Vibration>();
            }
        }
        
        public static SteamVR_Action_Single knuckles_grip
        {
            get
            {
                return SteamVR_Actions.p_knuckles_grip.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Boolean knuckles_grip_touch
        {
            get
            {
                return SteamVR_Actions.p_knuckles_grip_touch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean knuckles_button_A
        {
            get
            {
                return SteamVR_Actions.p_knuckles_button_A.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean knuckles_button_B
        {
            get
            {
                return SteamVR_Actions.p_knuckles_button_B.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean knuckles_button_A_touch
        {
            get
            {
                return SteamVR_Actions.p_knuckles_button_A_touch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean knuckles_button_B_touch
        {
            get
            {
                return SteamVR_Actions.p_knuckles_button_B_touch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Single knuckles_trigger
        {
            get
            {
                return SteamVR_Actions.p_knuckles_trigger.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Boolean knuckles_trigger_touch
        {
            get
            {
                return SteamVR_Actions.p_knuckles_trigger_touch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean knuckles_trigger_click
        {
            get
            {
                return SteamVR_Actions.p_knuckles_trigger_click.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vector2 knuckles_joystick
        {
            get
            {
                return SteamVR_Actions.p_knuckles_joystick.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Boolean knuckles_joystick_touch
        {
            get
            {
                return SteamVR_Actions.p_knuckles_joystick_touch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean knuckles_joystick_click
        {
            get
            {
                return SteamVR_Actions.p_knuckles_joystick_click.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vector2 knuckles_touchpad
        {
            get
            {
                return SteamVR_Actions.p_knuckles_touchpad.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Boolean knuckles_touchpad_touch
        {
            get
            {
                return SteamVR_Actions.p_knuckles_touchpad_touch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean knuckles_touchpad_press
        {
            get
            {
                return SteamVR_Actions.p_knuckles_touchpad_press.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Pose knuckles_pose
        {
            get
            {
                return SteamVR_Actions.p_knuckles_pose.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Boolean knuckles_grip_click
        {
            get
            {
                return SteamVR_Actions.p_knuckles_grip_click.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Single knuckles_touchpad_force
        {
            get
            {
                return SteamVR_Actions.p_knuckles_touchpad_force.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Skeleton knuckles_left_hand
        {
            get
            {
                return SteamVR_Actions.p_knuckles_left_hand.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Skeleton knuckles_right_hand
        {
            get
            {
                return SteamVR_Actions.p_knuckles_right_hand.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Vibration knuckles_haptic
        {
            get
            {
                return SteamVR_Actions.p_knuckles_haptic.GetCopy<SteamVR_Action_Vibration>();
            }
        }
        
        public static SteamVR_Action_Vector2 cosmos_joystick
        {
            get
            {
                return SteamVR_Actions.p_cosmos_joystick.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Boolean cosmos_joystick_touch
        {
            get
            {
                return SteamVR_Actions.p_cosmos_joystick_touch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean cosmos_joystick_click
        {
            get
            {
                return SteamVR_Actions.p_cosmos_joystick_click.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Single cosmos_trigger
        {
            get
            {
                return SteamVR_Actions.p_cosmos_trigger.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Boolean cosmos_trigger_touch
        {
            get
            {
                return SteamVR_Actions.p_cosmos_trigger_touch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean cosmos_trigger_click
        {
            get
            {
                return SteamVR_Actions.p_cosmos_trigger_click.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean cosmos_grip_click
        {
            get
            {
                return SteamVR_Actions.p_cosmos_grip_click.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean cosmos_menu
        {
            get
            {
                return SteamVR_Actions.p_cosmos_menu.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean cosmos_buttonAX
        {
            get
            {
                return SteamVR_Actions.p_cosmos_buttonAX.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean cosmos_buttonBY
        {
            get
            {
                return SteamVR_Actions.p_cosmos_buttonBY.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean cosmos_bumper
        {
            get
            {
                return SteamVR_Actions.p_cosmos_bumper.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Skeleton cosmos_left_hand
        {
            get
            {
                return SteamVR_Actions.p_cosmos_left_hand.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Skeleton cosmos_right_hand
        {
            get
            {
                return SteamVR_Actions.p_cosmos_right_hand.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Pose cosmos_pose
        {
            get
            {
                return SteamVR_Actions.p_cosmos_pose.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Vibration cosmos_haptic
        {
            get
            {
                return SteamVR_Actions.p_cosmos_haptic.GetCopy<SteamVR_Action_Vibration>();
            }
        }
        
        public static SteamVR_Action_Vector2 picoNeo_thumbstick
        {
            get
            {
                return SteamVR_Actions.p_picoNeo_thumbstick.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Boolean picoNeo_thumbstick_touch
        {
            get
            {
                return SteamVR_Actions.p_picoNeo_thumbstick_touch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean picoNeo_thumbstick_click
        {
            get
            {
                return SteamVR_Actions.p_picoNeo_thumbstick_click.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Single picoNeo_trigger
        {
            get
            {
                return SteamVR_Actions.p_picoNeo_trigger.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Boolean picoNeo_trigger_click
        {
            get
            {
                return SteamVR_Actions.p_picoNeo_trigger_click.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean picoNeo_grip_click
        {
            get
            {
                return SteamVR_Actions.p_picoNeo_grip_click.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean picoNeo_app
        {
            get
            {
                return SteamVR_Actions.p_picoNeo_app.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean picoNeo_system
        {
            get
            {
                return SteamVR_Actions.p_picoNeo_system.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean picoNeo_buttonYB
        {
            get
            {
                return SteamVR_Actions.p_picoNeo_buttonYB.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean picoNeo_buttonXA
        {
            get
            {
                return SteamVR_Actions.p_picoNeo_buttonXA.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Skeleton picoNeo_left_hand
        {
            get
            {
                return SteamVR_Actions.p_picoNeo_left_hand.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Skeleton picoNeo_right_hand
        {
            get
            {
                return SteamVR_Actions.p_picoNeo_right_hand.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Pose picoNeo_pose
        {
            get
            {
                return SteamVR_Actions.p_picoNeo_pose.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Vibration picoNeo_haptic
        {
            get
            {
                return SteamVR_Actions.p_picoNeo_haptic.GetCopy<SteamVR_Action_Vibration>();
            }
        }
        
        public static SteamVR_Action_Boolean hPReverb_appmenu
        {
            get
            {
                return SteamVR_Actions.p_hPReverb_appmenu.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean hPReverb_button_YB
        {
            get
            {
                return SteamVR_Actions.p_hPReverb_button_YB.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean hPReverb_button_XA
        {
            get
            {
                return SteamVR_Actions.p_hPReverb_button_XA.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Single hPReverb_grip
        {
            get
            {
                return SteamVR_Actions.p_hPReverb_grip.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Boolean hPReverb_grip_click
        {
            get
            {
                return SteamVR_Actions.p_hPReverb_grip_click.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean hPReverb_grip_touch
        {
            get
            {
                return SteamVR_Actions.p_hPReverb_grip_touch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vector2 hPReverb_joystick
        {
            get
            {
                return SteamVR_Actions.p_hPReverb_joystick.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Boolean hPReverb_joystick_click
        {
            get
            {
                return SteamVR_Actions.p_hPReverb_joystick_click.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Single hPReverb_trigger
        {
            get
            {
                return SteamVR_Actions.p_hPReverb_trigger.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Boolean hPReverb_trigger_click
        {
            get
            {
                return SteamVR_Actions.p_hPReverb_trigger_click.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Pose hPReverb_pose
        {
            get
            {
                return SteamVR_Actions.p_hPReverb_pose.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Skeleton hPReverb_left_hand
        {
            get
            {
                return SteamVR_Actions.p_hPReverb_left_hand.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Skeleton hPReverb_right_hand
        {
            get
            {
                return SteamVR_Actions.p_hPReverb_right_hand.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Vibration hPReverb_haptic
        {
            get
            {
                return SteamVR_Actions.p_hPReverb_haptic.GetCopy<SteamVR_Action_Vibration>();
            }
        }
        
        public static SteamVR_Action_Vector2 focus3_joystick
        {
            get
            {
                return SteamVR_Actions.p_focus3_joystick.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Boolean focus3_joystick_touch
        {
            get
            {
                return SteamVR_Actions.p_focus3_joystick_touch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean focus3_joystick_click
        {
            get
            {
                return SteamVR_Actions.p_focus3_joystick_click.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Single focus3_trigger
        {
            get
            {
                return SteamVR_Actions.p_focus3_trigger.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Boolean focus3_trigger_touch
        {
            get
            {
                return SteamVR_Actions.p_focus3_trigger_touch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean focus3_trigger_click
        {
            get
            {
                return SteamVR_Actions.p_focus3_trigger_click.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Single focus3_grip
        {
            get
            {
                return SteamVR_Actions.p_focus3_grip.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Boolean focus3_grip_touch
        {
            get
            {
                return SteamVR_Actions.p_focus3_grip_touch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean focus3_grip_click
        {
            get
            {
                return SteamVR_Actions.p_focus3_grip_click.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean focus3_button_a
        {
            get
            {
                return SteamVR_Actions.p_focus3_button_a.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean focus3_button_b
        {
            get
            {
                return SteamVR_Actions.p_focus3_button_b.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean focus3_button_x
        {
            get
            {
                return SteamVR_Actions.p_focus3_button_x.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean focus3_button_y
        {
            get
            {
                return SteamVR_Actions.p_focus3_button_y.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean focus3_menu
        {
            get
            {
                return SteamVR_Actions.p_focus3_menu.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean focus3_parking_touch
        {
            get
            {
                return SteamVR_Actions.p_focus3_parking_touch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Skeleton focus3_left_hand
        {
            get
            {
                return SteamVR_Actions.p_focus3_left_hand.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Skeleton focus3_right_hand
        {
            get
            {
                return SteamVR_Actions.p_focus3_right_hand.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Pose focus3_pose
        {
            get
            {
                return SteamVR_Actions.p_focus3_pose.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Vibration focus3_haptic
        {
            get
            {
                return SteamVR_Actions.p_focus3_haptic.GetCopy<SteamVR_Action_Vibration>();
            }
        }
        
        private static void InitializeActionArrays()
        {
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[] {
                    SteamVR_Actions.generic_Pose,
                    SteamVR_Actions.generic_Strength,
                    SteamVR_Actions.generic_Axis,
                    SteamVR_Actions.generic_TouchingStrength,
                    SteamVR_Actions.generic_TouchingAxis,
                    SteamVR_Actions.generic_ActionPrimary,
                    SteamVR_Actions.generic_ActionSecondary,
                    SteamVR_Actions.generic_ActionGrab,
                    SteamVR_Actions.generic_ActionMenu,
                    SteamVR_Actions.generic_LeftHand,
                    SteamVR_Actions.generic_RightHand,
                    SteamVR_Actions.generic_UserPresent,
                    SteamVR_Actions.generic_Haptic,
                    SteamVR_Actions.vive_trigger_hair,
                    SteamVR_Actions.vive_trigger_click,
                    SteamVR_Actions.vive_trigger,
                    SteamVR_Actions.vive_touchpad_touch,
                    SteamVR_Actions.vive_touchpad_click,
                    SteamVR_Actions.vive_touchpad,
                    SteamVR_Actions.vive_grip,
                    SteamVR_Actions.vive_app,
                    SteamVR_Actions.vive_pose,
                    SteamVR_Actions.vive_left_hand,
                    SteamVR_Actions.vive_right_hand,
                    SteamVR_Actions.vive_haptic,
                    SteamVR_Actions.oculusTouch_start,
                    SteamVR_Actions.oculusTouch_button_YB,
                    SteamVR_Actions.oculusTouch_button_XA,
                    SteamVR_Actions.oculusTouch_button_YB_touch,
                    SteamVR_Actions.oculusTouch_button_XA_touch,
                    SteamVR_Actions.oculusTouch_thumbrest_touch,
                    SteamVR_Actions.oculusTouch_grip,
                    SteamVR_Actions.oculusTouch_grip_click,
                    SteamVR_Actions.oculusTouch_joystick,
                    SteamVR_Actions.oculusTouch_joystick_touch,
                    SteamVR_Actions.oculusTouch_joystick_click,
                    SteamVR_Actions.oculusTouch_trigger,
                    SteamVR_Actions.oculusTouch_trigger_touch,
                    SteamVR_Actions.oculusTouch_trigger_click,
                    SteamVR_Actions.oculusTouch_pose,
                    SteamVR_Actions.oculusTouch_left_hand,
                    SteamVR_Actions.oculusTouch_right_hand,
                    SteamVR_Actions.oculusTouch_haptic,
                    SteamVR_Actions.windowsMR_grip,
                    SteamVR_Actions.windowsMR_app,
                    SteamVR_Actions.windowsMR_trigger_hair,
                    SteamVR_Actions.windowsMR_trigger_click,
                    SteamVR_Actions.windowsMR_trigger,
                    SteamVR_Actions.windowsMR_touchpad,
                    SteamVR_Actions.windowsMR_touchpad_touch,
                    SteamVR_Actions.windowsMR_touchpad_click,
                    SteamVR_Actions.windowsMR_joystick,
                    SteamVR_Actions.windowsMR_pose,
                    SteamVR_Actions.windowsMR_left_hand,
                    SteamVR_Actions.windowsMR_right_hand,
                    SteamVR_Actions.windowsMR_haptic,
                    SteamVR_Actions.knuckles_grip,
                    SteamVR_Actions.knuckles_grip_touch,
                    SteamVR_Actions.knuckles_button_A,
                    SteamVR_Actions.knuckles_button_B,
                    SteamVR_Actions.knuckles_button_A_touch,
                    SteamVR_Actions.knuckles_button_B_touch,
                    SteamVR_Actions.knuckles_trigger,
                    SteamVR_Actions.knuckles_trigger_touch,
                    SteamVR_Actions.knuckles_trigger_click,
                    SteamVR_Actions.knuckles_joystick,
                    SteamVR_Actions.knuckles_joystick_touch,
                    SteamVR_Actions.knuckles_joystick_click,
                    SteamVR_Actions.knuckles_touchpad,
                    SteamVR_Actions.knuckles_touchpad_touch,
                    SteamVR_Actions.knuckles_touchpad_press,
                    SteamVR_Actions.knuckles_pose,
                    SteamVR_Actions.knuckles_grip_click,
                    SteamVR_Actions.knuckles_touchpad_force,
                    SteamVR_Actions.knuckles_left_hand,
                    SteamVR_Actions.knuckles_right_hand,
                    SteamVR_Actions.knuckles_haptic,
                    SteamVR_Actions.cosmos_joystick,
                    SteamVR_Actions.cosmos_joystick_touch,
                    SteamVR_Actions.cosmos_joystick_click,
                    SteamVR_Actions.cosmos_trigger,
                    SteamVR_Actions.cosmos_trigger_touch,
                    SteamVR_Actions.cosmos_trigger_click,
                    SteamVR_Actions.cosmos_grip_click,
                    SteamVR_Actions.cosmos_menu,
                    SteamVR_Actions.cosmos_buttonAX,
                    SteamVR_Actions.cosmos_buttonBY,
                    SteamVR_Actions.cosmos_bumper,
                    SteamVR_Actions.cosmos_left_hand,
                    SteamVR_Actions.cosmos_right_hand,
                    SteamVR_Actions.cosmos_pose,
                    SteamVR_Actions.cosmos_haptic,
                    SteamVR_Actions.picoNeo_thumbstick,
                    SteamVR_Actions.picoNeo_thumbstick_touch,
                    SteamVR_Actions.picoNeo_thumbstick_click,
                    SteamVR_Actions.picoNeo_trigger,
                    SteamVR_Actions.picoNeo_trigger_click,
                    SteamVR_Actions.picoNeo_grip_click,
                    SteamVR_Actions.picoNeo_app,
                    SteamVR_Actions.picoNeo_system,
                    SteamVR_Actions.picoNeo_buttonYB,
                    SteamVR_Actions.picoNeo_buttonXA,
                    SteamVR_Actions.picoNeo_left_hand,
                    SteamVR_Actions.picoNeo_right_hand,
                    SteamVR_Actions.picoNeo_pose,
                    SteamVR_Actions.picoNeo_haptic,
                    SteamVR_Actions.hPReverb_appmenu,
                    SteamVR_Actions.hPReverb_button_YB,
                    SteamVR_Actions.hPReverb_button_XA,
                    SteamVR_Actions.hPReverb_grip,
                    SteamVR_Actions.hPReverb_grip_click,
                    SteamVR_Actions.hPReverb_grip_touch,
                    SteamVR_Actions.hPReverb_joystick,
                    SteamVR_Actions.hPReverb_joystick_click,
                    SteamVR_Actions.hPReverb_trigger,
                    SteamVR_Actions.hPReverb_trigger_click,
                    SteamVR_Actions.hPReverb_pose,
                    SteamVR_Actions.hPReverb_left_hand,
                    SteamVR_Actions.hPReverb_right_hand,
                    SteamVR_Actions.hPReverb_haptic,
                    SteamVR_Actions.focus3_joystick,
                    SteamVR_Actions.focus3_joystick_touch,
                    SteamVR_Actions.focus3_joystick_click,
                    SteamVR_Actions.focus3_trigger,
                    SteamVR_Actions.focus3_trigger_touch,
                    SteamVR_Actions.focus3_trigger_click,
                    SteamVR_Actions.focus3_grip,
                    SteamVR_Actions.focus3_grip_touch,
                    SteamVR_Actions.focus3_grip_click,
                    SteamVR_Actions.focus3_button_a,
                    SteamVR_Actions.focus3_button_b,
                    SteamVR_Actions.focus3_button_x,
                    SteamVR_Actions.focus3_button_y,
                    SteamVR_Actions.focus3_menu,
                    SteamVR_Actions.focus3_parking_touch,
                    SteamVR_Actions.focus3_left_hand,
                    SteamVR_Actions.focus3_right_hand,
                    SteamVR_Actions.focus3_pose,
                    SteamVR_Actions.focus3_haptic};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.generic_Pose,
                    SteamVR_Actions.generic_Strength,
                    SteamVR_Actions.generic_Axis,
                    SteamVR_Actions.generic_TouchingStrength,
                    SteamVR_Actions.generic_TouchingAxis,
                    SteamVR_Actions.generic_ActionPrimary,
                    SteamVR_Actions.generic_ActionSecondary,
                    SteamVR_Actions.generic_ActionGrab,
                    SteamVR_Actions.generic_ActionMenu,
                    SteamVR_Actions.generic_LeftHand,
                    SteamVR_Actions.generic_RightHand,
                    SteamVR_Actions.generic_UserPresent,
                    SteamVR_Actions.vive_trigger_hair,
                    SteamVR_Actions.vive_trigger_click,
                    SteamVR_Actions.vive_trigger,
                    SteamVR_Actions.vive_touchpad_touch,
                    SteamVR_Actions.vive_touchpad_click,
                    SteamVR_Actions.vive_touchpad,
                    SteamVR_Actions.vive_grip,
                    SteamVR_Actions.vive_app,
                    SteamVR_Actions.vive_pose,
                    SteamVR_Actions.vive_left_hand,
                    SteamVR_Actions.vive_right_hand,
                    SteamVR_Actions.oculusTouch_start,
                    SteamVR_Actions.oculusTouch_button_YB,
                    SteamVR_Actions.oculusTouch_button_XA,
                    SteamVR_Actions.oculusTouch_button_YB_touch,
                    SteamVR_Actions.oculusTouch_button_XA_touch,
                    SteamVR_Actions.oculusTouch_thumbrest_touch,
                    SteamVR_Actions.oculusTouch_grip,
                    SteamVR_Actions.oculusTouch_grip_click,
                    SteamVR_Actions.oculusTouch_joystick,
                    SteamVR_Actions.oculusTouch_joystick_touch,
                    SteamVR_Actions.oculusTouch_joystick_click,
                    SteamVR_Actions.oculusTouch_trigger,
                    SteamVR_Actions.oculusTouch_trigger_touch,
                    SteamVR_Actions.oculusTouch_trigger_click,
                    SteamVR_Actions.oculusTouch_pose,
                    SteamVR_Actions.oculusTouch_left_hand,
                    SteamVR_Actions.oculusTouch_right_hand,
                    SteamVR_Actions.windowsMR_grip,
                    SteamVR_Actions.windowsMR_app,
                    SteamVR_Actions.windowsMR_trigger_hair,
                    SteamVR_Actions.windowsMR_trigger_click,
                    SteamVR_Actions.windowsMR_trigger,
                    SteamVR_Actions.windowsMR_touchpad,
                    SteamVR_Actions.windowsMR_touchpad_touch,
                    SteamVR_Actions.windowsMR_touchpad_click,
                    SteamVR_Actions.windowsMR_joystick,
                    SteamVR_Actions.windowsMR_pose,
                    SteamVR_Actions.windowsMR_left_hand,
                    SteamVR_Actions.windowsMR_right_hand,
                    SteamVR_Actions.knuckles_grip,
                    SteamVR_Actions.knuckles_grip_touch,
                    SteamVR_Actions.knuckles_button_A,
                    SteamVR_Actions.knuckles_button_B,
                    SteamVR_Actions.knuckles_button_A_touch,
                    SteamVR_Actions.knuckles_button_B_touch,
                    SteamVR_Actions.knuckles_trigger,
                    SteamVR_Actions.knuckles_trigger_touch,
                    SteamVR_Actions.knuckles_trigger_click,
                    SteamVR_Actions.knuckles_joystick,
                    SteamVR_Actions.knuckles_joystick_touch,
                    SteamVR_Actions.knuckles_joystick_click,
                    SteamVR_Actions.knuckles_touchpad,
                    SteamVR_Actions.knuckles_touchpad_touch,
                    SteamVR_Actions.knuckles_touchpad_press,
                    SteamVR_Actions.knuckles_pose,
                    SteamVR_Actions.knuckles_grip_click,
                    SteamVR_Actions.knuckles_touchpad_force,
                    SteamVR_Actions.knuckles_left_hand,
                    SteamVR_Actions.knuckles_right_hand,
                    SteamVR_Actions.cosmos_joystick,
                    SteamVR_Actions.cosmos_joystick_touch,
                    SteamVR_Actions.cosmos_joystick_click,
                    SteamVR_Actions.cosmos_trigger,
                    SteamVR_Actions.cosmos_trigger_touch,
                    SteamVR_Actions.cosmos_trigger_click,
                    SteamVR_Actions.cosmos_grip_click,
                    SteamVR_Actions.cosmos_menu,
                    SteamVR_Actions.cosmos_buttonAX,
                    SteamVR_Actions.cosmos_buttonBY,
                    SteamVR_Actions.cosmos_bumper,
                    SteamVR_Actions.cosmos_left_hand,
                    SteamVR_Actions.cosmos_right_hand,
                    SteamVR_Actions.cosmos_pose,
                    SteamVR_Actions.picoNeo_thumbstick,
                    SteamVR_Actions.picoNeo_thumbstick_touch,
                    SteamVR_Actions.picoNeo_thumbstick_click,
                    SteamVR_Actions.picoNeo_trigger,
                    SteamVR_Actions.picoNeo_trigger_click,
                    SteamVR_Actions.picoNeo_grip_click,
                    SteamVR_Actions.picoNeo_app,
                    SteamVR_Actions.picoNeo_system,
                    SteamVR_Actions.picoNeo_buttonYB,
                    SteamVR_Actions.picoNeo_buttonXA,
                    SteamVR_Actions.picoNeo_left_hand,
                    SteamVR_Actions.picoNeo_right_hand,
                    SteamVR_Actions.picoNeo_pose,
                    SteamVR_Actions.hPReverb_appmenu,
                    SteamVR_Actions.hPReverb_button_YB,
                    SteamVR_Actions.hPReverb_button_XA,
                    SteamVR_Actions.hPReverb_grip,
                    SteamVR_Actions.hPReverb_grip_click,
                    SteamVR_Actions.hPReverb_grip_touch,
                    SteamVR_Actions.hPReverb_joystick,
                    SteamVR_Actions.hPReverb_joystick_click,
                    SteamVR_Actions.hPReverb_trigger,
                    SteamVR_Actions.hPReverb_trigger_click,
                    SteamVR_Actions.hPReverb_pose,
                    SteamVR_Actions.hPReverb_left_hand,
                    SteamVR_Actions.hPReverb_right_hand,
                    SteamVR_Actions.focus3_joystick,
                    SteamVR_Actions.focus3_joystick_touch,
                    SteamVR_Actions.focus3_joystick_click,
                    SteamVR_Actions.focus3_trigger,
                    SteamVR_Actions.focus3_trigger_touch,
                    SteamVR_Actions.focus3_trigger_click,
                    SteamVR_Actions.focus3_grip,
                    SteamVR_Actions.focus3_grip_touch,
                    SteamVR_Actions.focus3_grip_click,
                    SteamVR_Actions.focus3_button_a,
                    SteamVR_Actions.focus3_button_b,
                    SteamVR_Actions.focus3_button_x,
                    SteamVR_Actions.focus3_button_y,
                    SteamVR_Actions.focus3_menu,
                    SteamVR_Actions.focus3_parking_touch,
                    SteamVR_Actions.focus3_left_hand,
                    SteamVR_Actions.focus3_right_hand,
                    SteamVR_Actions.focus3_pose};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.ISteamVR_Action_Out[] {
                    SteamVR_Actions.generic_Haptic,
                    SteamVR_Actions.vive_haptic,
                    SteamVR_Actions.oculusTouch_haptic,
                    SteamVR_Actions.windowsMR_haptic,
                    SteamVR_Actions.knuckles_haptic,
                    SteamVR_Actions.cosmos_haptic,
                    SteamVR_Actions.picoNeo_haptic,
                    SteamVR_Actions.hPReverb_haptic,
                    SteamVR_Actions.focus3_haptic};
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[] {
                    SteamVR_Actions.generic_Haptic,
                    SteamVR_Actions.vive_haptic,
                    SteamVR_Actions.oculusTouch_haptic,
                    SteamVR_Actions.windowsMR_haptic,
                    SteamVR_Actions.knuckles_haptic,
                    SteamVR_Actions.cosmos_haptic,
                    SteamVR_Actions.picoNeo_haptic,
                    SteamVR_Actions.hPReverb_haptic,
                    SteamVR_Actions.focus3_haptic};
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[] {
                    SteamVR_Actions.generic_Pose,
                    SteamVR_Actions.vive_pose,
                    SteamVR_Actions.oculusTouch_pose,
                    SteamVR_Actions.windowsMR_pose,
                    SteamVR_Actions.knuckles_pose,
                    SteamVR_Actions.cosmos_pose,
                    SteamVR_Actions.picoNeo_pose,
                    SteamVR_Actions.hPReverb_pose,
                    SteamVR_Actions.focus3_pose};
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[] {
                    SteamVR_Actions.generic_TouchingStrength,
                    SteamVR_Actions.generic_TouchingAxis,
                    SteamVR_Actions.generic_ActionPrimary,
                    SteamVR_Actions.generic_ActionSecondary,
                    SteamVR_Actions.generic_ActionGrab,
                    SteamVR_Actions.generic_ActionMenu,
                    SteamVR_Actions.generic_UserPresent,
                    SteamVR_Actions.vive_trigger_hair,
                    SteamVR_Actions.vive_trigger_click,
                    SteamVR_Actions.vive_touchpad_touch,
                    SteamVR_Actions.vive_touchpad_click,
                    SteamVR_Actions.vive_grip,
                    SteamVR_Actions.vive_app,
                    SteamVR_Actions.oculusTouch_start,
                    SteamVR_Actions.oculusTouch_button_YB,
                    SteamVR_Actions.oculusTouch_button_XA,
                    SteamVR_Actions.oculusTouch_button_YB_touch,
                    SteamVR_Actions.oculusTouch_button_XA_touch,
                    SteamVR_Actions.oculusTouch_thumbrest_touch,
                    SteamVR_Actions.oculusTouch_grip_click,
                    SteamVR_Actions.oculusTouch_joystick_touch,
                    SteamVR_Actions.oculusTouch_joystick_click,
                    SteamVR_Actions.oculusTouch_trigger_touch,
                    SteamVR_Actions.oculusTouch_trigger_click,
                    SteamVR_Actions.windowsMR_grip,
                    SteamVR_Actions.windowsMR_app,
                    SteamVR_Actions.windowsMR_trigger_hair,
                    SteamVR_Actions.windowsMR_trigger_click,
                    SteamVR_Actions.windowsMR_touchpad_touch,
                    SteamVR_Actions.windowsMR_touchpad_click,
                    SteamVR_Actions.knuckles_grip_touch,
                    SteamVR_Actions.knuckles_button_A,
                    SteamVR_Actions.knuckles_button_B,
                    SteamVR_Actions.knuckles_button_A_touch,
                    SteamVR_Actions.knuckles_button_B_touch,
                    SteamVR_Actions.knuckles_trigger_touch,
                    SteamVR_Actions.knuckles_trigger_click,
                    SteamVR_Actions.knuckles_joystick_touch,
                    SteamVR_Actions.knuckles_joystick_click,
                    SteamVR_Actions.knuckles_touchpad_touch,
                    SteamVR_Actions.knuckles_touchpad_press,
                    SteamVR_Actions.knuckles_grip_click,
                    SteamVR_Actions.cosmos_joystick_touch,
                    SteamVR_Actions.cosmos_joystick_click,
                    SteamVR_Actions.cosmos_trigger_touch,
                    SteamVR_Actions.cosmos_trigger_click,
                    SteamVR_Actions.cosmos_grip_click,
                    SteamVR_Actions.cosmos_menu,
                    SteamVR_Actions.cosmos_buttonAX,
                    SteamVR_Actions.cosmos_buttonBY,
                    SteamVR_Actions.cosmos_bumper,
                    SteamVR_Actions.picoNeo_thumbstick_touch,
                    SteamVR_Actions.picoNeo_thumbstick_click,
                    SteamVR_Actions.picoNeo_trigger_click,
                    SteamVR_Actions.picoNeo_grip_click,
                    SteamVR_Actions.picoNeo_app,
                    SteamVR_Actions.picoNeo_system,
                    SteamVR_Actions.picoNeo_buttonYB,
                    SteamVR_Actions.picoNeo_buttonXA,
                    SteamVR_Actions.hPReverb_appmenu,
                    SteamVR_Actions.hPReverb_button_YB,
                    SteamVR_Actions.hPReverb_button_XA,
                    SteamVR_Actions.hPReverb_grip_click,
                    SteamVR_Actions.hPReverb_grip_touch,
                    SteamVR_Actions.hPReverb_joystick_click,
                    SteamVR_Actions.hPReverb_trigger_click,
                    SteamVR_Actions.focus3_joystick_touch,
                    SteamVR_Actions.focus3_joystick_click,
                    SteamVR_Actions.focus3_trigger_touch,
                    SteamVR_Actions.focus3_trigger_click,
                    SteamVR_Actions.focus3_grip_touch,
                    SteamVR_Actions.focus3_grip_click,
                    SteamVR_Actions.focus3_button_a,
                    SteamVR_Actions.focus3_button_b,
                    SteamVR_Actions.focus3_button_x,
                    SteamVR_Actions.focus3_button_y,
                    SteamVR_Actions.focus3_menu,
                    SteamVR_Actions.focus3_parking_touch};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[] {
                    SteamVR_Actions.generic_Strength,
                    SteamVR_Actions.vive_trigger,
                    SteamVR_Actions.oculusTouch_grip,
                    SteamVR_Actions.oculusTouch_trigger,
                    SteamVR_Actions.windowsMR_trigger,
                    SteamVR_Actions.knuckles_grip,
                    SteamVR_Actions.knuckles_trigger,
                    SteamVR_Actions.knuckles_touchpad_force,
                    SteamVR_Actions.cosmos_trigger,
                    SteamVR_Actions.picoNeo_trigger,
                    SteamVR_Actions.hPReverb_grip,
                    SteamVR_Actions.hPReverb_trigger,
                    SteamVR_Actions.focus3_trigger,
                    SteamVR_Actions.focus3_grip};
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[] {
                    SteamVR_Actions.generic_Axis,
                    SteamVR_Actions.vive_touchpad,
                    SteamVR_Actions.oculusTouch_joystick,
                    SteamVR_Actions.windowsMR_touchpad,
                    SteamVR_Actions.windowsMR_joystick,
                    SteamVR_Actions.knuckles_joystick,
                    SteamVR_Actions.knuckles_touchpad,
                    SteamVR_Actions.cosmos_joystick,
                    SteamVR_Actions.picoNeo_thumbstick,
                    SteamVR_Actions.hPReverb_joystick,
                    SteamVR_Actions.focus3_joystick};
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[] {
                    SteamVR_Actions.generic_LeftHand,
                    SteamVR_Actions.generic_RightHand,
                    SteamVR_Actions.vive_left_hand,
                    SteamVR_Actions.vive_right_hand,
                    SteamVR_Actions.oculusTouch_left_hand,
                    SteamVR_Actions.oculusTouch_right_hand,
                    SteamVR_Actions.windowsMR_left_hand,
                    SteamVR_Actions.windowsMR_right_hand,
                    SteamVR_Actions.knuckles_left_hand,
                    SteamVR_Actions.knuckles_right_hand,
                    SteamVR_Actions.cosmos_left_hand,
                    SteamVR_Actions.cosmos_right_hand,
                    SteamVR_Actions.picoNeo_left_hand,
                    SteamVR_Actions.picoNeo_right_hand,
                    SteamVR_Actions.hPReverb_left_hand,
                    SteamVR_Actions.hPReverb_right_hand,
                    SteamVR_Actions.focus3_left_hand,
                    SteamVR_Actions.focus3_right_hand};
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.generic_Strength,
                    SteamVR_Actions.generic_Axis,
                    SteamVR_Actions.generic_TouchingStrength,
                    SteamVR_Actions.generic_TouchingAxis,
                    SteamVR_Actions.generic_ActionPrimary,
                    SteamVR_Actions.generic_ActionSecondary,
                    SteamVR_Actions.generic_ActionGrab,
                    SteamVR_Actions.generic_ActionMenu,
                    SteamVR_Actions.generic_UserPresent,
                    SteamVR_Actions.vive_trigger_hair,
                    SteamVR_Actions.vive_trigger_click,
                    SteamVR_Actions.vive_trigger,
                    SteamVR_Actions.vive_touchpad_touch,
                    SteamVR_Actions.vive_touchpad_click,
                    SteamVR_Actions.vive_touchpad,
                    SteamVR_Actions.vive_grip,
                    SteamVR_Actions.vive_app,
                    SteamVR_Actions.oculusTouch_start,
                    SteamVR_Actions.oculusTouch_button_YB,
                    SteamVR_Actions.oculusTouch_button_XA,
                    SteamVR_Actions.oculusTouch_button_YB_touch,
                    SteamVR_Actions.oculusTouch_button_XA_touch,
                    SteamVR_Actions.oculusTouch_thumbrest_touch,
                    SteamVR_Actions.oculusTouch_grip,
                    SteamVR_Actions.oculusTouch_grip_click,
                    SteamVR_Actions.oculusTouch_joystick,
                    SteamVR_Actions.oculusTouch_joystick_touch,
                    SteamVR_Actions.oculusTouch_joystick_click,
                    SteamVR_Actions.oculusTouch_trigger,
                    SteamVR_Actions.oculusTouch_trigger_touch,
                    SteamVR_Actions.oculusTouch_trigger_click,
                    SteamVR_Actions.windowsMR_grip,
                    SteamVR_Actions.windowsMR_app,
                    SteamVR_Actions.windowsMR_trigger_hair,
                    SteamVR_Actions.windowsMR_trigger_click,
                    SteamVR_Actions.windowsMR_trigger,
                    SteamVR_Actions.windowsMR_touchpad,
                    SteamVR_Actions.windowsMR_touchpad_touch,
                    SteamVR_Actions.windowsMR_touchpad_click,
                    SteamVR_Actions.windowsMR_joystick,
                    SteamVR_Actions.knuckles_grip,
                    SteamVR_Actions.knuckles_grip_touch,
                    SteamVR_Actions.knuckles_button_A,
                    SteamVR_Actions.knuckles_button_B,
                    SteamVR_Actions.knuckles_button_A_touch,
                    SteamVR_Actions.knuckles_button_B_touch,
                    SteamVR_Actions.knuckles_trigger,
                    SteamVR_Actions.knuckles_trigger_touch,
                    SteamVR_Actions.knuckles_trigger_click,
                    SteamVR_Actions.knuckles_joystick,
                    SteamVR_Actions.knuckles_joystick_touch,
                    SteamVR_Actions.knuckles_joystick_click,
                    SteamVR_Actions.knuckles_touchpad,
                    SteamVR_Actions.knuckles_touchpad_touch,
                    SteamVR_Actions.knuckles_touchpad_press,
                    SteamVR_Actions.knuckles_grip_click,
                    SteamVR_Actions.knuckles_touchpad_force,
                    SteamVR_Actions.cosmos_joystick,
                    SteamVR_Actions.cosmos_joystick_touch,
                    SteamVR_Actions.cosmos_joystick_click,
                    SteamVR_Actions.cosmos_trigger,
                    SteamVR_Actions.cosmos_trigger_touch,
                    SteamVR_Actions.cosmos_trigger_click,
                    SteamVR_Actions.cosmos_grip_click,
                    SteamVR_Actions.cosmos_menu,
                    SteamVR_Actions.cosmos_buttonAX,
                    SteamVR_Actions.cosmos_buttonBY,
                    SteamVR_Actions.cosmos_bumper,
                    SteamVR_Actions.picoNeo_thumbstick,
                    SteamVR_Actions.picoNeo_thumbstick_touch,
                    SteamVR_Actions.picoNeo_thumbstick_click,
                    SteamVR_Actions.picoNeo_trigger,
                    SteamVR_Actions.picoNeo_trigger_click,
                    SteamVR_Actions.picoNeo_grip_click,
                    SteamVR_Actions.picoNeo_app,
                    SteamVR_Actions.picoNeo_system,
                    SteamVR_Actions.picoNeo_buttonYB,
                    SteamVR_Actions.picoNeo_buttonXA,
                    SteamVR_Actions.hPReverb_appmenu,
                    SteamVR_Actions.hPReverb_button_YB,
                    SteamVR_Actions.hPReverb_button_XA,
                    SteamVR_Actions.hPReverb_grip,
                    SteamVR_Actions.hPReverb_grip_click,
                    SteamVR_Actions.hPReverb_grip_touch,
                    SteamVR_Actions.hPReverb_joystick,
                    SteamVR_Actions.hPReverb_joystick_click,
                    SteamVR_Actions.hPReverb_trigger,
                    SteamVR_Actions.hPReverb_trigger_click,
                    SteamVR_Actions.focus3_joystick,
                    SteamVR_Actions.focus3_joystick_touch,
                    SteamVR_Actions.focus3_joystick_click,
                    SteamVR_Actions.focus3_trigger,
                    SteamVR_Actions.focus3_trigger_touch,
                    SteamVR_Actions.focus3_trigger_click,
                    SteamVR_Actions.focus3_grip,
                    SteamVR_Actions.focus3_grip_touch,
                    SteamVR_Actions.focus3_grip_click,
                    SteamVR_Actions.focus3_button_a,
                    SteamVR_Actions.focus3_button_b,
                    SteamVR_Actions.focus3_button_x,
                    SteamVR_Actions.focus3_button_y,
                    SteamVR_Actions.focus3_menu,
                    SteamVR_Actions.focus3_parking_touch};
        }
        
        private static void PreInitActions()
        {
            SteamVR_Actions.p_generic_Pose = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/Generic/in/Pose")));
            SteamVR_Actions.p_generic_Strength = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/Generic/in/Strength")));
            SteamVR_Actions.p_generic_Axis = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/Generic/in/Axis")));
            SteamVR_Actions.p_generic_TouchingStrength = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Generic/in/TouchingStrength")));
            SteamVR_Actions.p_generic_TouchingAxis = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Generic/in/TouchingAxis")));
            SteamVR_Actions.p_generic_ActionPrimary = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Generic/in/ActionPrimary")));
            SteamVR_Actions.p_generic_ActionSecondary = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Generic/in/ActionSecondary")));
            SteamVR_Actions.p_generic_ActionGrab = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Generic/in/ActionGrab")));
            SteamVR_Actions.p_generic_ActionMenu = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Generic/in/ActionMenu")));
            SteamVR_Actions.p_generic_LeftHand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/Generic/in/LeftHand")));
            SteamVR_Actions.p_generic_RightHand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/Generic/in/RightHand")));
            SteamVR_Actions.p_generic_UserPresent = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Generic/in/UserPresent")));
            SteamVR_Actions.p_generic_Haptic = ((SteamVR_Action_Vibration)(SteamVR_Action.Create<SteamVR_Action_Vibration>("/actions/Generic/out/Haptic")));
            SteamVR_Actions.p_vive_trigger_hair = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Vive/in/trigger_hair")));
            SteamVR_Actions.p_vive_trigger_click = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Vive/in/trigger_click")));
            SteamVR_Actions.p_vive_trigger = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/Vive/in/trigger")));
            SteamVR_Actions.p_vive_touchpad_touch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Vive/in/touchpad_touch")));
            SteamVR_Actions.p_vive_touchpad_click = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Vive/in/touchpad_click")));
            SteamVR_Actions.p_vive_touchpad = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/Vive/in/touchpad")));
            SteamVR_Actions.p_vive_grip = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Vive/in/grip")));
            SteamVR_Actions.p_vive_app = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Vive/in/app")));
            SteamVR_Actions.p_vive_pose = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/Vive/in/pose")));
            SteamVR_Actions.p_vive_left_hand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/Vive/in/left_hand")));
            SteamVR_Actions.p_vive_right_hand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/Vive/in/right_hand")));
            SteamVR_Actions.p_vive_haptic = ((SteamVR_Action_Vibration)(SteamVR_Action.Create<SteamVR_Action_Vibration>("/actions/Vive/out/haptic")));
            SteamVR_Actions.p_oculusTouch_start = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/OculusTouch/in/start")));
            SteamVR_Actions.p_oculusTouch_button_YB = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/OculusTouch/in/button_YB")));
            SteamVR_Actions.p_oculusTouch_button_XA = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/OculusTouch/in/button_XA")));
            SteamVR_Actions.p_oculusTouch_button_YB_touch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/OculusTouch/in/button_YB_touch")));
            SteamVR_Actions.p_oculusTouch_button_XA_touch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/OculusTouch/in/button_XA_touch")));
            SteamVR_Actions.p_oculusTouch_thumbrest_touch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/OculusTouch/in/thumbrest_touch")));
            SteamVR_Actions.p_oculusTouch_grip = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/OculusTouch/in/grip")));
            SteamVR_Actions.p_oculusTouch_grip_click = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/OculusTouch/in/grip_click")));
            SteamVR_Actions.p_oculusTouch_joystick = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/OculusTouch/in/joystick")));
            SteamVR_Actions.p_oculusTouch_joystick_touch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/OculusTouch/in/joystick_touch")));
            SteamVR_Actions.p_oculusTouch_joystick_click = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/OculusTouch/in/joystick_click")));
            SteamVR_Actions.p_oculusTouch_trigger = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/OculusTouch/in/trigger")));
            SteamVR_Actions.p_oculusTouch_trigger_touch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/OculusTouch/in/trigger_touch")));
            SteamVR_Actions.p_oculusTouch_trigger_click = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/OculusTouch/in/trigger_click")));
            SteamVR_Actions.p_oculusTouch_pose = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/OculusTouch/in/pose")));
            SteamVR_Actions.p_oculusTouch_left_hand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/OculusTouch/in/left_hand")));
            SteamVR_Actions.p_oculusTouch_right_hand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/OculusTouch/in/right_hand")));
            SteamVR_Actions.p_oculusTouch_haptic = ((SteamVR_Action_Vibration)(SteamVR_Action.Create<SteamVR_Action_Vibration>("/actions/OculusTouch/out/haptic")));
            SteamVR_Actions.p_windowsMR_grip = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/WindowsMR/in/grip")));
            SteamVR_Actions.p_windowsMR_app = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/WindowsMR/in/app")));
            SteamVR_Actions.p_windowsMR_trigger_hair = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/WindowsMR/in/trigger_hair")));
            SteamVR_Actions.p_windowsMR_trigger_click = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/WindowsMR/in/trigger_click")));
            SteamVR_Actions.p_windowsMR_trigger = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/WindowsMR/in/trigger")));
            SteamVR_Actions.p_windowsMR_touchpad = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/WindowsMR/in/touchpad")));
            SteamVR_Actions.p_windowsMR_touchpad_touch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/WindowsMR/in/touchpad_touch")));
            SteamVR_Actions.p_windowsMR_touchpad_click = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/WindowsMR/in/touchpad_click")));
            SteamVR_Actions.p_windowsMR_joystick = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/WindowsMR/in/joystick")));
            SteamVR_Actions.p_windowsMR_pose = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/WindowsMR/in/pose")));
            SteamVR_Actions.p_windowsMR_left_hand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/WindowsMR/in/left_hand")));
            SteamVR_Actions.p_windowsMR_right_hand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/WindowsMR/in/right_hand")));
            SteamVR_Actions.p_windowsMR_haptic = ((SteamVR_Action_Vibration)(SteamVR_Action.Create<SteamVR_Action_Vibration>("/actions/WindowsMR/out/haptic")));
            SteamVR_Actions.p_knuckles_grip = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/Knuckles/in/grip")));
            SteamVR_Actions.p_knuckles_grip_touch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Knuckles/in/grip_touch")));
            SteamVR_Actions.p_knuckles_button_A = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Knuckles/in/button_A")));
            SteamVR_Actions.p_knuckles_button_B = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Knuckles/in/button_B")));
            SteamVR_Actions.p_knuckles_button_A_touch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Knuckles/in/button_A_touch")));
            SteamVR_Actions.p_knuckles_button_B_touch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Knuckles/in/button_B-touch")));
            SteamVR_Actions.p_knuckles_trigger = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/Knuckles/in/trigger")));
            SteamVR_Actions.p_knuckles_trigger_touch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Knuckles/in/trigger_touch")));
            SteamVR_Actions.p_knuckles_trigger_click = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Knuckles/in/trigger_click")));
            SteamVR_Actions.p_knuckles_joystick = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/Knuckles/in/joystick")));
            SteamVR_Actions.p_knuckles_joystick_touch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Knuckles/in/joystick_touch")));
            SteamVR_Actions.p_knuckles_joystick_click = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Knuckles/in/joystick_click")));
            SteamVR_Actions.p_knuckles_touchpad = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/Knuckles/in/touchpad")));
            SteamVR_Actions.p_knuckles_touchpad_touch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Knuckles/in/touchpad_touch")));
            SteamVR_Actions.p_knuckles_touchpad_press = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Knuckles/in/touchpad_press")));
            SteamVR_Actions.p_knuckles_pose = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/Knuckles/in/pose")));
            SteamVR_Actions.p_knuckles_grip_click = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Knuckles/in/grip_click")));
            SteamVR_Actions.p_knuckles_touchpad_force = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/Knuckles/in/touchpad_force")));
            SteamVR_Actions.p_knuckles_left_hand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/Knuckles/in/left_hand")));
            SteamVR_Actions.p_knuckles_right_hand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/Knuckles/in/right_hand")));
            SteamVR_Actions.p_knuckles_haptic = ((SteamVR_Action_Vibration)(SteamVR_Action.Create<SteamVR_Action_Vibration>("/actions/Knuckles/out/haptic")));
            SteamVR_Actions.p_cosmos_joystick = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/Cosmos/in/joystick")));
            SteamVR_Actions.p_cosmos_joystick_touch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Cosmos/in/joystick_touch")));
            SteamVR_Actions.p_cosmos_joystick_click = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Cosmos/in/joystick_click")));
            SteamVR_Actions.p_cosmos_trigger = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/Cosmos/in/trigger")));
            SteamVR_Actions.p_cosmos_trigger_touch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Cosmos/in/trigger_touch")));
            SteamVR_Actions.p_cosmos_trigger_click = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Cosmos/in/trigger_click")));
            SteamVR_Actions.p_cosmos_grip_click = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Cosmos/in/grip_click")));
            SteamVR_Actions.p_cosmos_menu = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Cosmos/in/menu")));
            SteamVR_Actions.p_cosmos_buttonAX = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Cosmos/in/buttonAX")));
            SteamVR_Actions.p_cosmos_buttonBY = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Cosmos/in/buttonBY")));
            SteamVR_Actions.p_cosmos_bumper = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Cosmos/in/bumper")));
            SteamVR_Actions.p_cosmos_left_hand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/Cosmos/in/left_hand")));
            SteamVR_Actions.p_cosmos_right_hand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/Cosmos/in/right_hand")));
            SteamVR_Actions.p_cosmos_pose = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/Cosmos/in/pose")));
            SteamVR_Actions.p_cosmos_haptic = ((SteamVR_Action_Vibration)(SteamVR_Action.Create<SteamVR_Action_Vibration>("/actions/Cosmos/out/haptic")));
            SteamVR_Actions.p_picoNeo_thumbstick = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/PicoNeo/in/thumbstick")));
            SteamVR_Actions.p_picoNeo_thumbstick_touch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/PicoNeo/in/thumbstick_touch")));
            SteamVR_Actions.p_picoNeo_thumbstick_click = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/PicoNeo/in/thumbstick_click")));
            SteamVR_Actions.p_picoNeo_trigger = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/PicoNeo/in/trigger")));
            SteamVR_Actions.p_picoNeo_trigger_click = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/PicoNeo/in/trigger_click")));
            SteamVR_Actions.p_picoNeo_grip_click = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/PicoNeo/in/grip_click")));
            SteamVR_Actions.p_picoNeo_app = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/PicoNeo/in/app")));
            SteamVR_Actions.p_picoNeo_system = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/PicoNeo/in/system")));
            SteamVR_Actions.p_picoNeo_buttonYB = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/PicoNeo/in/buttonYB")));
            SteamVR_Actions.p_picoNeo_buttonXA = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/PicoNeo/in/buttonXA")));
            SteamVR_Actions.p_picoNeo_left_hand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/PicoNeo/in/left_hand")));
            SteamVR_Actions.p_picoNeo_right_hand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/PicoNeo/in/right_hand")));
            SteamVR_Actions.p_picoNeo_pose = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/PicoNeo/in/pose")));
            SteamVR_Actions.p_picoNeo_haptic = ((SteamVR_Action_Vibration)(SteamVR_Action.Create<SteamVR_Action_Vibration>("/actions/PicoNeo/out/haptic")));
            SteamVR_Actions.p_hPReverb_appmenu = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/HPReverb/in/appmenu")));
            SteamVR_Actions.p_hPReverb_button_YB = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/HPReverb/in/button_YB")));
            SteamVR_Actions.p_hPReverb_button_XA = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/HPReverb/in/button_XA")));
            SteamVR_Actions.p_hPReverb_grip = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/HPReverb/in/grip")));
            SteamVR_Actions.p_hPReverb_grip_click = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/HPReverb/in/grip_click")));
            SteamVR_Actions.p_hPReverb_grip_touch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/HPReverb/in/grip_touch")));
            SteamVR_Actions.p_hPReverb_joystick = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/HPReverb/in/joystick")));
            SteamVR_Actions.p_hPReverb_joystick_click = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/HPReverb/in/joystick_click")));
            SteamVR_Actions.p_hPReverb_trigger = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/HPReverb/in/trigger")));
            SteamVR_Actions.p_hPReverb_trigger_click = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/HPReverb/in/trigger_click")));
            SteamVR_Actions.p_hPReverb_pose = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/HPReverb/in/pose")));
            SteamVR_Actions.p_hPReverb_left_hand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/HPReverb/in/left_hand")));
            SteamVR_Actions.p_hPReverb_right_hand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/HPReverb/in/right_hand")));
            SteamVR_Actions.p_hPReverb_haptic = ((SteamVR_Action_Vibration)(SteamVR_Action.Create<SteamVR_Action_Vibration>("/actions/HPReverb/out/haptic")));
            SteamVR_Actions.p_focus3_joystick = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/Focus3/in/joystick")));
            SteamVR_Actions.p_focus3_joystick_touch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Focus3/in/joystick_touch")));
            SteamVR_Actions.p_focus3_joystick_click = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Focus3/in/joystick_click")));
            SteamVR_Actions.p_focus3_trigger = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/Focus3/in/trigger")));
            SteamVR_Actions.p_focus3_trigger_touch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Focus3/in/trigger_touch")));
            SteamVR_Actions.p_focus3_trigger_click = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Focus3/in/trigger_click")));
            SteamVR_Actions.p_focus3_grip = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/Focus3/in/grip")));
            SteamVR_Actions.p_focus3_grip_touch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Focus3/in/grip_touch")));
            SteamVR_Actions.p_focus3_grip_click = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Focus3/in/grip_click")));
            SteamVR_Actions.p_focus3_button_a = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Focus3/in/button_a")));
            SteamVR_Actions.p_focus3_button_b = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Focus3/in/button_b")));
            SteamVR_Actions.p_focus3_button_x = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Focus3/in/button_x")));
            SteamVR_Actions.p_focus3_button_y = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Focus3/in/button_y")));
            SteamVR_Actions.p_focus3_menu = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Focus3/in/menu")));
            SteamVR_Actions.p_focus3_parking_touch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Focus3/in/parking_touch")));
            SteamVR_Actions.p_focus3_left_hand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/Focus3/in/left_hand")));
            SteamVR_Actions.p_focus3_right_hand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/Focus3/in/right_hand")));
            SteamVR_Actions.p_focus3_pose = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/Focus3/in/pose")));
            SteamVR_Actions.p_focus3_haptic = ((SteamVR_Action_Vibration)(SteamVR_Action.Create<SteamVR_Action_Vibration>("/actions/Focus3/out/haptic")));
        }
    }
}
