//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Focus3 : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Vector2 joystick
        {
            get
            {
                return SteamVR_Actions.focus3_joystick;
            }
        }
        
        public virtual SteamVR_Action_Boolean joystick_touch
        {
            get
            {
                return SteamVR_Actions.focus3_joystick_touch;
            }
        }
        
        public virtual SteamVR_Action_Boolean joystick_click
        {
            get
            {
                return SteamVR_Actions.focus3_joystick_click;
            }
        }
        
        public virtual SteamVR_Action_Single trigger
        {
            get
            {
                return SteamVR_Actions.focus3_trigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean trigger_touch
        {
            get
            {
                return SteamVR_Actions.focus3_trigger_touch;
            }
        }
        
        public virtual SteamVR_Action_Boolean trigger_click
        {
            get
            {
                return SteamVR_Actions.focus3_trigger_click;
            }
        }
        
        public virtual SteamVR_Action_Single grip
        {
            get
            {
                return SteamVR_Actions.focus3_grip;
            }
        }
        
        public virtual SteamVR_Action_Boolean grip_touch
        {
            get
            {
                return SteamVR_Actions.focus3_grip_touch;
            }
        }
        
        public virtual SteamVR_Action_Boolean grip_click
        {
            get
            {
                return SteamVR_Actions.focus3_grip_click;
            }
        }
        
        public virtual SteamVR_Action_Boolean button_a
        {
            get
            {
                return SteamVR_Actions.focus3_button_a;
            }
        }
        
        public virtual SteamVR_Action_Boolean button_b
        {
            get
            {
                return SteamVR_Actions.focus3_button_b;
            }
        }
        
        public virtual SteamVR_Action_Boolean button_x
        {
            get
            {
                return SteamVR_Actions.focus3_button_x;
            }
        }
        
        public virtual SteamVR_Action_Boolean button_y
        {
            get
            {
                return SteamVR_Actions.focus3_button_y;
            }
        }
        
        public virtual SteamVR_Action_Boolean menu
        {
            get
            {
                return SteamVR_Actions.focus3_menu;
            }
        }
        
        public virtual SteamVR_Action_Boolean parking_touch
        {
            get
            {
                return SteamVR_Actions.focus3_parking_touch;
            }
        }
        
        public virtual SteamVR_Action_Skeleton left_hand
        {
            get
            {
                return SteamVR_Actions.focus3_left_hand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton right_hand
        {
            get
            {
                return SteamVR_Actions.focus3_right_hand;
            }
        }
        
        public virtual SteamVR_Action_Pose pose
        {
            get
            {
                return SteamVR_Actions.focus3_pose;
            }
        }
        
        public virtual SteamVR_Action_Vibration haptic
        {
            get
            {
                return SteamVR_Actions.focus3_haptic;
            }
        }
    }
}
